In [1]:
name = "HKU"

In [2]:
year = 2

In [3]:
print(name, year)

HKU 2

In [4]:
x = 10

In [5]:
x = x + 5

In [6]:
print(x)

15

# CyberGuard AI

This notebook explores cybersecurity logs

In [7]:
numbers = [1,2,3,4,5]
numbers

[1, 2, 3, 4, 5]

In [8]:
import os

os.path.getsize("students.csv")

62

In [9]:
import pandas as pd
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   20     90
1      Bob   21     85
2  Charlie   19     95
3    David   22     88

In [16]:
df.shape

(4, 3)

In [10]:
df.head()

      Name  Age  Score
0    Alice   20     90
1      Bob   21     85
2  Charlie   19     95
3    David   22     88

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [ ]:
df.describe()

             Age      Score
count   4.000000   4.000000
mean   20.500000  89.500000
std     1.290994   4.203173
min    19.000000  85.000000
25%    19.750000  87.250000
50%    20.500000  89.000000
75%    21.250000  91.250000
max    22.000000  95.000000

In [18]:
df[["Name", "Score"]]

      Name  Score
0    Alice     90
1      Bob     85
2  Charlie     95
3    David     88

In [20]:
df[df["Score"] > 88]

      Name  Age  Score
0    Alice   20     90
2  Charlie   19     95

In [21]:
df.sort_values(by="Score", ascending=False)

      Name  Age  Score
2  Charlie   19     95
0    Alice   20     90
3    David   22     88
1      Bob   21     85

In [23]:
df["Pass"] = df["Score"] >= 90
df

      Name  Age  Score   Pass
0    Alice   20     90   True
1      Bob   21     85  False
2  Charlie   19     95   True
3    David   22     88  False

In [24]:
df["Score"].value_counts()

Score
90    1
85    1
95    1
88    1
Name: count, dtype: int64

In [ ]:
#exercise 21
#combined filtering
df[(df["Score"] >= 90) & (df["Age"] <= 20)]

      Name  Age  Score  Pass
0    Alice   20     90  True
2  Charlie   19     95  True

In [ ]:
#exercise 22
df[df["Score"] == max(df["Score"])]

      Name  Age  Score  Pass
2  Charlie   19     95  True

In [36]:
#OR
df2=df.sort_values(by="Score", ascending=False)
df2.head(1)

      Name  Age  Score  Pass
2  Charlie   19     95  True

In [40]:
df3=pd.read_csv("students2.csv")
df3

      Name   Age  Score
0    Alice  20.0   90.0
1      Bob   NaN   85.0
2  Charlie  19.0   95.0
3    David  22.0    NaN

In [ ]:
#data wrangling

#exercise 16
df3.isnull().sum()

Name     0
Age      1
Score    1
dtype: int64

In [ ]:
df3_clean = df3.dropna()
df3_clean

      Name   Age  Score
0    Alice  20.0   90.0
2  Charlie  19.0   95.0

In [45]:
#exercise 17
df3["Age"] = df3["Age"].fillna(20)
df3

      Name   Age  Score
0    Alice  20.0   90.0
1      Bob  20.0   85.0
2  Charlie  19.0   95.0
3    David  22.0    NaN

In [49]:
#exercise 18
df3["Age"] = df3["Age"].astype(str)
df3

      Name   Age  Score
0    Alice  20.0   90.0
1      Bob  20.0   85.0
2  Charlie  19.0   95.0
3    David  22.0    NaN

In [53]:
df3["Age"] = df3["Age"].astype(float)
df3

      Name   Age  Score
0    Alice  20.0   90.0
1      Bob  20.0   85.0
2  Charlie  19.0   95.0
3    David  22.0    NaN

In [54]:
df3["Age"] = df3["Age"].astype(int)
df3

      Name  Age  Score
0    Alice   20   90.0
1      Bob   20   85.0
2  Charlie   19   95.0
3    David   22    NaN

In [56]:
df3["High_Performer"] = df3["Score"] >= 90
df3

      Name  Age  Score  High_Performer
0    Alice   20   90.0            True
1      Bob   20   85.0           False
2  Charlie   19   95.0            True
3    David   22    NaN           False