In [1]:
import pandas as pd
df=pd.read_csv("../data/cybersecurity_cleaned.csv")

In [2]:
#need dictionary
unique_protocol = df["protocol"].unique().tolist()
unique_protocol_List = []
for item in unique_protocol:
    unique_protocol_List.append(item)
unique_protocol_List

['TCP', 'UDP', 'ICMP']

In [3]:
protocol_dict = {}
for item in unique_protocol_List:
    protocol_dict[item] = unique_protocol_List.index(item)
protocol_dict

{'TCP': 0, 'UDP': 1, 'ICMP': 2}

In [4]:
#to retrieve the numbers
protocol_List = list(protocol_dict.values())
protocol_List

[0, 1, 2]

In [5]:
unique_IsInternalTraffic = df["is_internal_traffic"].unique().tolist()
unique_IsInternalTraffic

[False, True]

In [6]:
#not to be used in training
#retrieves all unique label values in the dataset
unique_label = df["label"].unique().tolist()
unique_label

[0, 1]

In [7]:
#not to be used in training
#retrieves all attack_type values in the dataset
unique_attack_type = df["attack_type"].unique().tolist()
unique_attack_type

['benign',
 'port-scan',
 'c2',
 'credential-stuffing',
 'brute-force',
 'command-injection',
 'sql-injection',
 'xss',
 'exploit-attempt',
 'ddos']

In [8]:
#assume works
df["timestamp"] = df["timestamp"].astype("datetime64[s]")
df

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
3,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign
4,2025-10-01 01:19:57,238.229.195.174,16.182.72.24,25167,443,TCP,3592,1081,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,https://internal.bank.local/?id=432022,True,0,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6763,2025-12-29 22:35:29,100.3.151.108,249.17.98.177,44655,3306,TCP,102224,161909,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://webmail.corp/admin?id=667076,False,0,benign
6764,2025-12-29 22:51:57,152.9.53.114,236.104.126.125,3306,22,UDP,244511,280085,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=120556,True,0,benign
6765,2025-12-29 23:03:05,213.54.194.229,216.34.37.197,3389,445,TCP,10597,16670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://app.company.in/api/v1/users?id=525850,False,0,benign
6766,2025-12-29 23:20:46,19.12.213.100,243.249.117.224,31882,80,TCP,6062,3504,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,https://app.company.in/manager/html?id=497838,False,0,benign
6767,2025-12-29 23:26:12,161.251.147.82,107.163.89.174,52607,3389,TCP,335446,442720,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/api/v1/users?id=315734,False,0,benign

In [9]:
#for src_ip and dst_ip
df["src_ip"] = df["src_ip"].str.replace('.','')
df["src_ip"] = df["src_ip"].astype(int)
df

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,18817627165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68592643,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:27:21,122119194175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
3,2025-10-01 00:40:09,18119924268,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign
4,2025-10-01 01:19:57,238229195174,16.182.72.24,25167,443,TCP,3592,1081,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,https://internal.bank.local/?id=432022,True,0,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6763,2025-12-29 22:35:29,1003151108,249.17.98.177,44655,3306,TCP,102224,161909,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://webmail.corp/admin?id=667076,False,0,benign
6764,2025-12-29 22:51:57,152953114,236.104.126.125,3306,22,UDP,244511,280085,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=120556,True,0,benign
6765,2025-12-29 23:03:05,21354194229,216.34.37.197,3389,445,TCP,10597,16670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://app.company.in/api/v1/users?id=525850,False,0,benign
6766,2025-12-29 23:20:46,1912213100,243.249.117.224,31882,80,TCP,6062,3504,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,https://app.company.in/manager/html?id=497838,False,0,benign
6767,2025-12-29 23:26:12,16125114782,107.163.89.174,52607,3389,TCP,335446,442720,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/api/v1/users?id=315734,False,0,benign

In [10]:
#for src_ip and dst_ip
df["dst_ip"] = df["dst_ip"].str.replace('.','')
df["dst_ip"] = df["dst_ip"].astype(int)
df

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,18817627165,253240113218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68592643,2127538111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:27:21,122119194175,17514078230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
3,2025-10-01 00:40:09,18119924268,559917769,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign
4,2025-10-01 01:19:57,238229195174,161827224,25167,443,TCP,3592,1081,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,https://internal.bank.local/?id=432022,True,0,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6763,2025-12-29 22:35:29,1003151108,2491798177,44655,3306,TCP,102224,161909,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://webmail.corp/admin?id=667076,False,0,benign
6764,2025-12-29 22:51:57,152953114,236104126125,3306,22,UDP,244511,280085,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=120556,True,0,benign
6765,2025-12-29 23:03:05,21354194229,2163437197,3389,445,TCP,10597,16670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://app.company.in/api/v1/users?id=525850,False,0,benign
6766,2025-12-29 23:20:46,1912213100,243249117224,31882,80,TCP,6062,3504,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,https://app.company.in/manager/html?id=497838,False,0,benign
6767,2025-12-29 23:26:12,16125114782,10716389174,52607,3389,TCP,335446,442720,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/api/v1/users?id=315734,False,0,benign

In [11]:
df["is_internal_traffic"] = df["is_internal_traffic"].astype(int)
df

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,18817627165,253240113218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,0,0,benign
1,2025-10-01 00:23:43,68592643,2127538111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,0,0,benign
2,2025-10-01 00:27:21,122119194175,17514078230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,0,0,benign
3,2025-10-01 00:40:09,18119924268,559917769,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,0,0,benign
4,2025-10-01 01:19:57,238229195174,161827224,25167,443,TCP,3592,1081,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,https://internal.bank.local/?id=432022,1,0,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6763,2025-12-29 22:35:29,1003151108,2491798177,44655,3306,TCP,102224,161909,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://webmail.corp/admin?id=667076,0,0,benign
6764,2025-12-29 22:51:57,152953114,236104126125,3306,22,UDP,244511,280085,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=120556,1,0,benign
6765,2025-12-29 23:03:05,21354194229,2163437197,3389,445,TCP,10597,16670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://app.company.in/api/v1/users?id=525850,0,0,benign
6766,2025-12-29 23:20:46,1912213100,243249117224,31882,80,TCP,6062,3504,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,https://app.company.in/manager/html?id=497838,0,0,benign
6767,2025-12-29 23:26:12,16125114782,10716389174,52607,3389,TCP,335446,442720,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/api/v1/users?id=315734,0,0,benign

In [12]:
df["protocol"] = df["protocol"].replace(protocol_dict)
df["protocol"] = df["protocol"].astype(int)
df

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,18817627165,253240113218,56377,445,0,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,0,0,benign
1,2025-10-01 00:23:43,68592643,2127538111,51165,1433,0,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,0,0,benign
2,2025-10-01 00:27:21,122119194175,17514078230,36097,443,0,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,0,0,benign
3,2025-10-01 00:40:09,18119924268,559917769,445,21255,0,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,0,0,benign
4,2025-10-01 01:19:57,238229195174,161827224,25167,443,0,3592,1081,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,https://internal.bank.local/?id=432022,1,0,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6763,2025-12-29 22:35:29,1003151108,2491798177,44655,3306,0,102224,161909,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://webmail.corp/admin?id=667076,0,0,benign
6764,2025-12-29 22:51:57,152953114,236104126125,3306,22,1,244511,280085,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=120556,1,0,benign
6765,2025-12-29 23:03:05,21354194229,2163437197,3389,445,0,10597,16670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://app.company.in/api/v1/users?id=525850,0,0,benign
6766,2025-12-29 23:20:46,1912213100,243249117224,31882,80,0,6062,3504,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,https://app.company.in/manager/html?id=497838,0,0,benign
6767,2025-12-29 23:26:12,16125114782,10716389174,52607,3389,0,335446,442720,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/api/v1/users?id=315734,0,0,benign

In [13]:
#checking
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6768 entries, 0 to 6767
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            6768 non-null   datetime64[s]
 1   src_ip               6768 non-null   int64
 2   dst_ip               6768 non-null   int64
 3   src_port             6768 non-null   int64
 4   dst_port             6768 non-null   int64
 5   protocol             6768 non-null   int64
 6   bytes_sent           6768 non-null   int64
 7   bytes_received       6768 non-null   int64
 8   user_agent           6768 non-null   str
 9   url                  6768 non-null   str
 10  is_internal_traffic  6768 non-null   int64
 11  label                6768 non-null   int64
 12  attack_type          6768 non-null   str
dtypes: datetime64[s](1), int64(9), str(3)
memory usage: 1.6 MB

In [14]:
df.isnull().sum()

timestamp              0
src_ip                 0
dst_ip                 0
src_port               0
dst_port               0
protocol               0
bytes_sent             0
bytes_received         0
user_agent             0
url                    0
is_internal_traffic    0
label                  0
attack_type            0
dtype: int64

In [15]:
df.to_csv("../data/cybersecurity_engineered.csv", index=False)

print("Feature Engineering Complete")

Feature Engineering Complete